@startuml Email

class Email {
    - id: UUID
    - ownerRef: String
    - emailTo: String
    - subject: String
    - text: String
    - fileUrl: String
    - sendDate: LocalDateTime
}

enum EmailStatus {
    + PROCESSING
    + SENT
    + ERROR
}

enum EmailType {
    + DEFAULT
    + RESET_PASSWOR
}

Email "*" o-> "1" EmailType
Email "*" o-> "1" EmailStatus


@enduml