spring:
  datasource.url: ${DATABASE_URL}
  datasource.driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: update

  jpa.open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com